name = "example"
version = "0.0.1"
authors = ["Your Name <your_name@mail.com>"]

shebang = "#!/usr/bin/env zsh"
permission = "0755"


# 主命令 - greet
[[commands]]
name = "greet"
about = "向用户打招呼"

# greet 命令的参数定义
args = [
    {name = "name", short = "n", long = "name", help = "要打招呼的人的名字", required = true, takes_value = true},
    {name = "times", short = "t", long = "times", help = "重复打招呼的次数", required = false, takes_value = true, default = "1"},
    {name = "loud", short = "l", long = "loud", help = "使用大写字母", required = false, takes_value = false}
]

# greet 命令的子命令 - morning
[[commands.subcommands]]
name = "morning"
about = "早上好的特殊问候"
args = [
    {name = "name", short = "n", long = "name", help = "要打招呼的人的名字", required = true, takes_value = true}
]

# 另一个主命令 - config
[[commands]]
name = "config"
about = "配置管理"

[[commands.subcommands]]
name = "set"
about = "设置配置项"
args = [
    {name = "key", help = "配置项的键", required = true, takes_value = true, position = 0},
    {name = "value", help = "配置项的值", required = true, takes_value = true, position = 1}
]

[[commands.subcommands]]
name = "get"
about = "获取配置项"
args = [
    {name = "key", help = "配置项的键", required = true, takes_value = true, position = 0}
]
